language: node_js

cache:
  bundler: true
  directories:
  - node_modules
  - /home/travis/.rvm/
  - _site/

node_js:
  - "node"

rvm:
  - "2.2"

before_install:
  - mv _site/.jekyll-metadata .jekyll-metadata 2>/dev/null || true
  - bundle install

before_script:
  - bundle exec jekyll build --incremental --verbose

before_cache:
  - mv .jekyll-metadata _site/.jekyll-metadata
