name: Lint JavaScript files

on:
  push:
    paths:
      - "package*.json"
      - ".eslintrc.json"
      - "**/*.js"
      - ".github/workflows/lint-js.yml"
    branches-ignore:
      - "dependabot/**"
  pull_request:
    paths:
      - "package*.json"
      - ".eslintrc.json"
      - "**/*.js"
      - ".github/workflows/lint-js.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 10

      - name: Install Node dependencies
        run: npm ci

      - name: Run Node tests
        run: npm run lint:js
